### ISSUE TITLE
Why did you switch from Rollup to Webpack?

### ISSUE THREAD

**Issue by tarjei** [EmilTholin/svelte-test#1]
Hi, just a quick question here - why did you switch from Rollup to webpack? Some special bugs you encountered - or just out of curiosity? I'm looking into Svelte myself and thought it would be usefull to find out why you chose webpack over rollup?

Regards
Tarjei

**Comment by EmilTholin** [comment]
Hi Tarjei!

I switched simply because I have more experience with Webpack. I didn't know how to get ExtractText and templating to work with Rollup, but I'm sure there is a way to go about it.

**Comment by tarjei** [comment]
Great answer - thanks :)
